config/routes.rb
Rails.application.routes.draw do
  post 'things/borrow', to: 'borrowings#create', as: 'borrow'
  post 'things/return', to: 'borrowings#finish', as: 'return'

  get 'things/:id/add_project', to: 'project_things_relations#new', as: 'add_thing_to_project'

  get '/material/:id', to: 'materials#change_amount', as: 'change_amount'

  get 'raports/new'

  post '/project_section_relations/create', to: 'project_section_relations#create', as: 'add_project_to_section'

  post 'project/coordinate', to: 'projects#update', as: 'coordinate_project'
  post 'project/destroy_member', to: 'project_memberships#destroy', as: 'destroy_project_member'
  post 'project/add_member', to: 'project_memberships#create', as: 'create_project_member'
  get 'project/:id/add_member', to: 'project_memberships#new', as: 'new_project_member'

  post '/new_project', to: 'projects#create'
  get '/new_project', to: 'projects#new'

  post 'sections/index/coordinate', to: 'sections#update', as: 'coordinate'

  get 'sections/index'

  post 'section_memberships/create', to: 'section_memberships#create', as: 'add_membership'

  post 'section_memberships/destroy', to: 'section_memberships#destroy', as: 'destroy_membership'

  get '/activate/:id', to: 'account_activations#activate', as: 'activate'
  get '/promote/:id', to: 'account_activations#promote_to_member', as: 'promote'

  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/about',  to: 'static_pages#about'

  get '/rules', to: 'static_pages#rules'

root 'static_pages#home'

resources :users
resources :section_memberships, only: [:destroy, :create]
resources :sections, only: [:index, :show]
resources :projects, only: [:index, :show, :new, :update, :destroy]
resources :raports, only: [:new, :show, :create]
resources :materials
resources :object_types
resources :things
resources :project_things_relations, only: [:create, :destroy]


end

app/models/thing.rb
class Thing < ApplicationRecord
  validates :serial_number, presence: true, uniqueness: true,
            length: { maximum: 50 }
  validates :state, presence: true
  belongs_to :object_type
  belongs_to :supervisor, class_name: "User"
  has_many :project_things_relations
  has_many :projects, through: :project_things_relations
  has_many :borrowings
  has_many :borrowers, through: :borrowings, source: :user


  def borrower
    self.borrowers.last
  end

  def self.search(pattern)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    elsif pattern == "#wypożyczony"
      joins(:borrowings).where(borrowings: {returned_at: nil})
    else
      left_outer_joins(:supervisor,:object_type).where(
        "CAST(things.id AS TEXT) LIKE ? OR
         things.note LIKE ? OR
         object_types.name LIKE ? OR
         things.state LIKE ? OR
         things.serial_number LIKE ? OR
         users.name || ' ' || users.surname LIKE ?",
        "#{pattern}","%#{pattern}%","%#{pattern}%",
        "%#{pattern}%","%#{pattern}%",
        "#{pattern}")
    end
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
    before_action :logged_in_user, only: [:index, :show]
    before_action :member_user, only: [:new, :create, :edit, :update]

    def new
      @thing = Thing.new(supervisor_id: current_user.id, state: "nowy")
      @object_types = ObjectType.all
    end

    def create
      @thing = Thing.new(thing_params)
      if @thing.save
        flash[:success] = "Egzemplarz dodany pomyślnie!"
        redirect_to things_path
      else
        flash[:danger] = "Numer seryjny zajęty lub pusty"
        redirect_to new_thing_path
      end
    end

    def update
      @thing = Thing.find(params[:id])
      if @thing.update_attributes(thing_params)
         flash[:success] = "Egzemplarz pomyślnie zaktualizowany"
        redirect_to @thing
      else
        redirect_to edit_thing_path(@thing)
      end
    end

    def show
      @thing = Thing.find(params[:id])
      @supervisor = @thing.supervisor
      @borrower = @thing.borrower
    end

    def index
      @things = Thing.search(params[:term]).paginate(page: params[:page])
    end

    def edit
      @thing = Thing.find(params[:id])
      @states = list_states
      @object_types = ObjectType.all
    end


  def define_supervisor
  end




  private
  def thing_params
    params.require(:thing).permit(:serial_number, :supervisor_id, :note, :object_type_id, :state)
  end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/define_supervisor.html.erb
<h1>Things#define_supervisor</h1>
<p>Find me in app/views/things/define_supervisor.html.erb</p>

app/views/things/edit.html.erb
<% provide(:title, "Edycja przedmiotu") %>
<h1>Edytuj dane przedmiotu</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@thing, url: thing_path(@thing)) do |f| %>

      <%= f.label :serial_number, "Numer seryjny" %>
      <%= f.text_field :serial_number, class: 'form-control' %>

      <%= f.label :object_type_id, "Typ przedmiotu" %>
      <%=  f.collection_select(:object_type_id, @object_types, :id, :name) %>

      <%= f.label :state, "Stan" %>
      <%=  f.collection_select(:state, @states, :to_s, :to_s) %>
      <%= f.hidden_field  :supervisor_id  %>

      <h2>Opcjonalne</h2>
      <%= f.label :note, "Uwagi" %>
      <%= f.text_field :note, class: 'form-control' %>

      <%= f.submit "Wyślij formularz", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/things/index.html.erb
<% provide(:title, 'Egzemplarze') %>
<h1>Posiadane przez koło przedmioty</h1>

<%= form_tag(things_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>


<%= will_paginate %>
<% if current_user.member?  %>
  <h2><%= link_to "Dodaj przedmiot", new_thing_path %></h2>
<% end%>
<ol class="sections">
  <% @things.each do |thing| %>
      <li>
            <%= link_to thing.serial_number, thing_path(thing)  %>
            <%= " #{thing.object_type.name} |  stan: #{thing.state}" %>
            <% if current_user.member? %>
                     <% if thing.borrowings.where(returned_at: nil).empty? %>
                        |  <%= link_to 'Wypożycz', borrow_path(borrow: {thing_id: thing.id,
                                               user_id: current_user.id}), method: :post %>
                     <% end %>
            <% end %>
      </li>
    <% end %>
</ol>
<%= will_paginate %>

app/views/things/new.html.erb
<% provide(:title, 'Dodaj przedmiot') %>
<h1>Wprowadź cechy przedmiotu</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@thing, url: things_path) do |f| %>

      <%= f.label :serial_number, "Numer seryjny" %>
      <%= f.text_field :serial_number, class: 'form-control' %>

      <%=  f.collection_select(:object_type_id, @object_types, :id, :name) %>
      <%= f.hidden_field  :supervisor_id  %>
      <%= f.hidden_field  :state  %>

      <h2>Opcjonalne</h2>
      <%= f.label :note, "Uwagi" %>
      <%= f.text_field :note, class: 'form-control' %>

      <%= f.submit "Wyślij formularz", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/things/show.html.erb
<% provide(:title, @thing.serial_number) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @thing.serial_number %>
        <% if current_user.member? %>
         <%= link_to "(Edytuj)", edit_thing_path(@thing) %>
        <%end%>
      </h1>
      <h2><%= @thing.object_type.name %></h2>
      </br>
        Status: <%= @thing.state %>
        <% if current_user.member? %>
          <% if @thing.borrowings.where(returned_at: nil).empty? %>
               |  <%= link_to 'Wypożycz', borrow_path(borrow: {thing_id: @thing.id,
                                    user_id: current_user.id}), method: :post %>
          <% end %>
        <% end %>
        <% if !@borrower.nil? %>
        </br>Wypożyczony przez <%= link_to "#{@borrower.name} #{@borrower.surname}", user_path(@borrower) %> <%=
                                      "#{@thing.borrowings.last.created_at}" %>
        <% end %>
        </br>
        Opiekun: <%= "#{@supervisor.name} #{@supervisor.surname}" %></br>
        Kategoria: <%=  @thing.object_type.category %></br>
        Przyporządkowany do projektów: <% if  @thing.projects.empty?  %>
        <%= "---" %>
          <% else %>
          <ol>
          <% @thing.projects.each do |project| %>
          <li>
            <%= link_to project.name, project_path(project)  %>
          </li>
          <% end %>
          </ol>
        <% end %>
        <%= link_to "(dodaj do projektu)", add_thing_to_project_path(@thing) if current_user.member? %>
        </br>
        Data dodania: <%=  @thing.created_at %></br>
        Data ostatniej modyfikacji: <%=  @thing.updated_at %></br>
        Uwagi: <%= @thing.note %>
      </br>
    </section>
  </aside>
</div>