config/routes.rb
Rails.application.routes.draw do
  post 'things/borrow', to: 'borrowings#create', as: 'borrow'
  post 'things/return', to: 'borrowings#finish', as: 'return'

  get 'things/:id/add_project', to: 'project_things_relations#new', as: 'add_thing_to_project'

  get '/material/:id', to: 'materials#change_amount', as: 'change_amount'

  get 'raports/new'

  post '/project_section_relations/create', to: 'project_section_relations#create', as: 'add_project_to_section'

  post 'project/coordinate', to: 'projects#update', as: 'coordinate_project'
  post 'project/destroy_member', to: 'project_memberships#destroy', as: 'destroy_project_member'
  post 'project/add_member', to: 'project_memberships#create', as: 'create_project_member'
  get 'project/:id/add_member', to: 'project_memberships#new', as: 'new_project_member'

  post '/new_project', to: 'projects#create'
  get '/new_project', to: 'projects#new'

  post 'sections/index/coordinate', to: 'sections#update', as: 'coordinate'

  get 'sections/index'

  post 'section_memberships/create', to: 'section_memberships#create', as: 'add_membership'

  post 'section_memberships/destroy', to: 'section_memberships#destroy', as: 'destroy_membership'

  get '/activate/:id', to: 'account_activations#activate', as: 'activate'
  get '/promote/:id', to: 'account_activations#promote_to_member', as: 'promote'

  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/about',  to: 'static_pages#about'

  get '/rules', to: 'static_pages#rules'

root 'static_pages#home'

resources :users
resources :section_memberships, only: [:destroy, :create]
resources :sections, only: [:index, :show]
resources :projects, only: [:index, :show, :new, :update, :destroy]
resources :raports, only: [:new, :show, :create]
resources :materials
resources :object_types
resources :things
resources :project_things_relations, only: [:create, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email.downcase! }

  default_scope -> { order(:surname, :name)}
  validates :name, presence: true, length: { maximum: 50 }
  validates :surname, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /[\w+\-.]+@[a-z\d\-.]*[a-z\d]\.[a-z]+/i
  validates :email, presence: true,
            length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true



  has_many :section_memberships,   foreign_key: "member_id"
  has_many :sections, through: :section_memberships
  has_many :coordinates, class_name: "Section", foreign_key: "coordinator_id"

  has_many :project_memberships,   foreign_key: "member_id"
  has_many :projects, through: :project_memberships
  has_many :coordinates_projects, class_name: "Project", foreign_key: "coordinator_id"

  has_many :raports, foreign_key: "author_id"

  has_many :materials, foreign_key: "supervisor_id"

  has_many :things, foreign_key: "supervisor_id"

  has_many :borrowings
  has_many :borrowed, through: :borrowings, source: :thing


  def self.new_token
     SecureRandom.urlsafe_base64
   end

   def remember
       self.remember_token = User.new_token
       update_attribute(:remember_digest, User.digest(remember_token))
     end

     def authenticated?(remember_token)
      return false if self.remember_digest.nil?
         BCrypt::Password.new(remember_digest).is_password?(remember_token)
       end

  def forget
      update_attribute(:remember_digest, nil)
    end

  def self.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
  end

  def currently_borrowed
    borrowings = self.borrowings.where(returned_at: nil)
    borrowed_things = []
    borrowings.each do |borrowing|
      borrowed_things << borrowing.thing
    end
    borrowed_things
  end

  def self.search(pattern)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      if pattern == "#aktywny"
        where(activated: true)
      elsif pattern == "#koordynator"
        where(coordinator: true)
      elsif pattern == "#członek"
        where(member: true)
      elsif pattern == "#opiekun"
        where(supervisor: true)
      else
        where(
          "CAST(users.id AS TEXT) LIKE ? OR
           users.name LIKE ? OR
           users.surname LIKE ? OR
           users.name || ' ' || users.surname LIKE ? OR
           users.phone_number LIKE ?",
          "#{pattern}","%#{pattern}%","%#{pattern}%",
          "%#{pattern}%","%#{pattern}%")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :coordinator_user,     only: [:destroy]


  def new
    @user = User.new
  end

  def show
      @user=User.find(params[:id])
      @section_membership = @user.section_memberships.build(member_id: @user.id) if current_user.coordinator?
      @sections = []
      if current_user.coordinator?
        Section.find_each do |section|
          @sections << section if !section.members.include?(@user)
        end
      end
  end

  def index
    @users = User.search(params[:term]).paginate(page: params[:page])
  end

  def destroy
      User.find(params[:id]).destroy
      flash[:success] = "Użytkownik usunięty"
      redirect_to users_url
    end


  def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "Konto utworzone pomyślnie!"
        redirect_to root_path
      else
        render 'new'
      end
    end

    def edit
       @user = User.find(params[:id])
     end


     def update
       @user = User.find(params[:id])
       if @user.update_attributes(user_params)
          flash[:success] = "Profil pomyślnie zaktualizowany"
         redirect_to @user
       else
         render 'edit'
       end
     end

    private

      def user_params
        params.require(:user).permit(:name, :surname, :email, :password,
                                     :password_confirmation, :phone_number)
      end



      def correct_user
       @user = User.find(params[:id])
       redirect_to(root_url) unless current_user?(@user) || current_user.coordinator?
      end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edycja profilu") %>
<h1>Edytuj swoje dane</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
        <%= f.label :name, "Imię" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :surname, "Nazwisko"%>
        <%= f.text_field :surname, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password, "Hasło" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Potwierdź hasło" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <h2>Dane dodatkowe</h2>
        <%= f.label :phone_number, "Numer telefonu" %>
        <%= f.text_field :phone_number, class: 'form-control' %>

        <%= f.submit "Wyślij formularz", class: "btn btn-primary" %>
      <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Użytkownicy') %>
<h1>Lista użytkowników</h1>

<%= form_tag(users_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.name} #{user.surname}", user %>
      <% if current_user.coordinator? && !current_user?(user) %>
          | <%= link_to "Usuń konto", user, method: :delete,
                                        data: { confirm: "Czy aby na pewno usunąć użytkownika?" } %>
      <% end %>
      <% if current_user.coordinator? && !user.activated? %>
          | <%= link_to "Aktywuj", activate_path(user) %>
        <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Rejestracja') %>
<h1>Wprowadź swoje dane</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages'%>

      <%= f.label :name, "Imię" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :surname, "Nazwisko"%>
      <%= f.text_field :surname, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Hasło" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Potwierdź hasło" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <h2>Dane dodatkowe</h2>
      <%= f.label :phone_number, "Numer telefonu" %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.submit "Wyślij formularz", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %> <%= @user.surname %>
        <% if @user == current_user || current_user.coordinator? %>
         <%= link_to "(Edytuj)", edit_user_path(@user) %>
        <%end%>
      </h1>
      <h2>
        <% if @user.coordinator? %>
        Koordynator
        <% elsif @user.member? %>
        Członek
        <% elsif @user.supervisor? %>
        Opiekun koła
        <% elsif @user.activated? %>
        Rekrut
        <% else %>
        Konto nieaktywne
        <% end %>
      </h2>
      </br>
        Email: <%= @user.email %></br>
        Numer telefonu: <%=  @user.phone_number.blank? ? "---" : @user.phone_number%></br>
        Sekcje: <% if  @user.sections.empty?  %>
        <%= "---" %>
          <% else @user.sections.each do |section| %>
          <%= section.name  %>
          <% end %>
        <% end %>
        </br>
        Data wstąpienia: <%=  @user.activated_at.nil? ? "---" : @user.activated_at%></br>
        <% if current_user.coordinator? && @user.activated? %>
          <% if @user.member? %>
            <%= form_for(@section_membership, url: add_membership_path) do |f| %>
              <%= f.label :section_id, "Dołącz użytkownika do sekcji" %>
              <%=  f.collection_select(:section_id, @sections, :id, :name) %>
              <%= f.hidden_field  :member_id  %>
              <%= f.submit "Dodaj", class: "btn btn-primary" %>
            <%end%>
          <%else%>
            Nie można dołączyć do sekcji, gdy nie jest członkiem
            <%= link_to "Mianuj członkiem", promote_path(@user) %>
          <%end%>
        <%end%>
      </br>
    </section>
  </aside>
</div>
<h1> Projekty </h1>
<ol class="sections">
  <% @user.projects.each do |project| %>
      <li>
            <%= link_to project.name, project_path(project)  %>
            <%= " | Zakończony" unless project.finished_at.nil? %>
      </li>
    <% end %>
</ol>
<h1> Sprawozdania </h1>
<ol class="sections">
  <% @user.raports.each do |raport| %>
      <li>
            <%= link_to raport.created_at, raport_path(raport)  %>
            <%= "Projekt: #{raport.project.name}" %>
      </li>
    <% end %>
</ol>
<h1>Materiały za które jest odpowiedzialny</h1>
<ol class="sections">
  <% @user.materials.each do |material| %>
      <li>
            <%= link_to material.name, material_path(material)  %>
      </li>
    <% end %>
</ol>
<h1>Przedmioty za które jest odpowiedzialny</h1>
<ol class="sections">
  <% @user.things.each do |thing| %>
      <li>
            <%= link_to thing.serial_number, thing_path(thing)  %>
            <%= " | #{thing.object_type.name}" %>
      </li>
    <% end %>
</ol>
<h1>Wypożyczone przedmioty</h1>
<ol class="sections">
  <% @user.currently_borrowed.each do |thing| %>
      <li>
            <%= link_to thing.serial_number, thing_path(thing)  %>
            <%= " | #{thing.object_type.name}" %>
            <%= " | #{thing.borrowings.last.created_at}" %>
            <% if current_user == @user %>
              <%= link_to "Zwróć", return_path(thing_id: thing.id), method: :post %>
            <% end %>
      </li>
    <% end %>
</ol>