config/routes.rb
Rails.application.routes.draw do
  post 'things/borrow', to: 'borrowings#create', as: 'borrow'
  post 'things/return', to: 'borrowings#finish', as: 'return'

  get 'things/:id/add_project', to: 'project_things_relations#new', as: 'add_thing_to_project'

  get '/material/:id', to: 'materials#change_amount', as: 'change_amount'

  get 'raports/new'

  post '/project_section_relations/create', to: 'project_section_relations#create', as: 'add_project_to_section'

  post 'project/coordinate', to: 'projects#update', as: 'coordinate_project'
  post 'project/destroy_member', to: 'project_memberships#destroy', as: 'destroy_project_member'
  post 'project/add_member', to: 'project_memberships#create', as: 'create_project_member'
  get 'project/:id/add_member', to: 'project_memberships#new', as: 'new_project_member'

  post '/new_project', to: 'projects#create'
  get '/new_project', to: 'projects#new'

  post 'sections/index/coordinate', to: 'sections#update', as: 'coordinate'

  get 'sections/index'

  post 'section_memberships/create', to: 'section_memberships#create', as: 'add_membership'

  post 'section_memberships/destroy', to: 'section_memberships#destroy', as: 'destroy_membership'

  get '/activate/:id', to: 'account_activations#activate', as: 'activate'
  get '/promote/:id', to: 'account_activations#promote_to_member', as: 'promote'

  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/about',  to: 'static_pages#about'

  get '/rules', to: 'static_pages#rules'

root 'static_pages#home'

resources :users
resources :section_memberships, only: [:destroy, :create]
resources :sections, only: [:index, :show]
resources :projects, only: [:index, :show, :new, :update, :destroy]
resources :raports, only: [:new, :show, :create]
resources :materials
resources :object_types
resources :things
resources :project_things_relations, only: [:create, :destroy]


end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true

  belongs_to :coordinator, class_name: "User", optional: true

  has_many :members, through: :project_memberships, source: :member
  has_many :project_memberships, foreign_key: "project_id"

  has_many :sections, through: :project_section_relations
  has_many :project_section_relations, foreign_key: "project_id"

  has_many :raports, foreign_key: "project_id"

  has_many :project_things_relations
  has_many :things, through: :project_things_relations

  def self.search(pattern)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      left_outer_joins(:coordinator).where(
        "projects.name LIKE ? OR
         users.name || ' ' || users.surname
         LIKE ? OR
        CAST(projects.id AS TEXT) LIKE ?",
        "%#{pattern}%","%#{pattern}%",
        "#{pattern}")
    end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user
  before_action :coordinator_user, only: [:update, :new, :create, :destroy]

  def index
    @projects = Project.search(params[:term])
  end

  def show

    @project = Project.find_by(id: params[:id])
    @members = @project.members.paginate(page: params[:page])
    @relations = @project.project_memberships
    @raports = @project.raports
    @things = @project.things

    @section_membership = @project.project_section_relations.build(project_id: @project.id) if current_user.coordinator?
    @sections = []
    if current_user.coordinator?
      Section.find_each do |section|
        @sections << section if !section.projects.include?(@project)
      end
    end
  end

  def create
      @project = Project.new(project_params)
      if @project.save
        flash[:success] = "Projekt dodany pomyślnie!"
        redirect_to projects_path
      else
        flash[:danger] = "Prawdpodobnie ta nazwa jest już zajęta"
        render 'new'
      end
    end

  def update
    project = Project.find_by(id: params[:project_id])
    user = User.find_by(id: params[:member_id])
    project.coordinator = user
    if project.save
      flash[:success] = "Użytkownik mianonowany koordynatorem"
    else
      flash[:danger] = "błąd!"
    end
    redirect_to project_path(params[:project_id])
  end

  def new
    @project = Project.new
  end

  def destroy
    @project = Project.find_by(id: params[:id])
    @project.finished_at = Time.now.utc
    if @project.save
      flash[:success] = "Projekt zarchiwzowany!"
    else
      flash[:danger] = "Błąd!"
    end
    redirect_to projects_path
  end

private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<% provide(:title, "Projekty") %>

<%= form_tag(projects_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>


<% if current_user.coordinator?  %>
  <h1><%= link_to "Dodaj projekt", new_project_path %></h1>
<% end%>
<ol class="sections">
  <% @projects.each do |project| %>
      <li>
            <%= link_to project.name, project_path(project)  %>
            <%= " | Zakończony" unless project.finished_at.nil? %>

            <% if current_user.coordinator && project.finished_at.nil?%>
                | <%= link_to "Archiwizuj", project_path(project) , method: :delete,
                                              data: { confirm: "Czy aby na pewno zarchiwizować projekt?" } %>
            <% end %>
      </li>
    <% end %>
</ol>

app/views/projects/new.html.erb
<% provide(:title, 'Nowy projekt') %>
<h1>Wprowadź dane projektu</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project, url: new_project_path) do |f| %>

      <%= f.label :name, "Nazwa projektu" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Wyślij formularz", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<% provide(:title, "Projekt #{@project.name}") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @project.name %>
      </h1>
      <h2>
        Kierownik: <%= @project.coordinator_id.nil? ? "---" : "#{User.find(@project.coordinator_id).name} #{User.find(@project.coordinator_id).surname}" %>
      </h2>
      </br>
        Sekcje: <% if  @project.sections.empty?  %>
        <%= "---" %>
          <% else @project.sections.each do |section| %>
          <%= section.name %>
          <% end %>
        <% end %>
        </br>
        Data rozpoczęcia: <%=  @project.created_at %></br>
        <%= "Data zakończenia: #{@project.finished_at}\n" unless @project.finished_at.nil? %>
        <% if current_user.coordinator? && @project.finished_at.nil? %>
            <%= form_for(@section_membership, url: add_project_to_section_path) do |f| %>
              <%= f.label :section_id, "Dołącz projekt do sekcji" %>
              <%=  f.collection_select(:section_id, @sections, :id, :name) %>
              <%= f.hidden_field  :project_id  %>
              <%= f.submit "Dodaj", class: "btn btn-primary" %>
            <% end %>
        <% end %>
      </br>
    </section>
  </aside>
</div>

<h1>Lista członków <%= link_to "(Dodaj)", new_project_member_path if current_user.coordinator? %></h1>

<ul class="users">
  <% @members.each do |member| %>
    <li <%= 'class=coordinator' if @project.coordinator == member %>>
      <%= link_to "#{member.name} #{member.surname}", member %>
        Dołączył: <%= @relations.find_by(member_id: member.id).created_at %>
        <% if @relations.find_by(member_id: member.id).historical? %>
           <%= "|   Zaprzestanie działalności: #{@relations.find_by(member_id: member.id).updated_at}" %>
        <% elsif current_user.coordinator? %>
          <%= link_to "|   Usuń z projektu", destroy_project_member_path(member_id: member.id, project_id: @project.id),
                                                method: :post, data: { confirm: "Czy aby na pewno usunąć użytkownika?" } %>
            <% if (current_user == @project.coordinator && member != @project.coordinator) || (current_user.coordinator? && @project.coordinator_id.nil?) %>
              <%= link_to "|   Uczyń kierownikiem", coordinate_project_path(member_id: member.id, project_id: @project.id),
                                       method: :post, data: { confirm: "Czy na pewno mianować kierownikiem?" } %>
            <% end %>
        <% end %>

    </li>
  <% end %>
</ul>

<h1>Lista sprawozdań <%= link_to "(Dodaj)", new_raport_path(project_id: @project.id) if current_user.projects.include?(@project) %></h1>

<ol class="sections">
  <% @raports.each do |raport| %>
      <li>
            <%= link_to raport.created_at , raport_path(raport)  %>
            <%= User.find_by(id: raport.author_id).surname %>
      </li>
    <% end %>
</ol>

<h1>Lista przyporządkowanych przedmiotów</h1>

<ol class="sections">
  <% @things.each do |thing| %>
      <li>
            <%= link_to thing.serial_number , thing_path(thing)  %> |
            <%= link_to "Odłącz od projektu", project_things_relation_path(ProjectThingsRelation.find_by(project_id: @project.id, thing_id: thing.id)), method: :delete, data: { confirm: "Czy na pewno usunąć przedmiot z projektu?" } %>
      </li>
    <% end %>
</ol>