config/routes.rb
Rails.application.routes.draw do
  post 'things/borrow', to: 'borrowings#create', as: 'borrow'
  post 'things/return', to: 'borrowings#finish', as: 'return'

  get 'things/:id/add_project', to: 'project_things_relations#new', as: 'add_thing_to_project'

  get '/material/:id', to: 'materials#change_amount', as: 'change_amount'

  get 'raports/new'

  post '/project_section_relations/create', to: 'project_section_relations#create', as: 'add_project_to_section'

  post 'project/coordinate', to: 'projects#update', as: 'coordinate_project'
  post 'project/destroy_member', to: 'project_memberships#destroy', as: 'destroy_project_member'
  post 'project/add_member', to: 'project_memberships#create', as: 'create_project_member'
  get 'project/:id/add_member', to: 'project_memberships#new', as: 'new_project_member'

  post '/new_project', to: 'projects#create'
  get '/new_project', to: 'projects#new'

  post 'sections/index/coordinate', to: 'sections#update', as: 'coordinate'

  get 'sections/index'

  post 'section_memberships/create', to: 'section_memberships#create', as: 'add_membership'

  post 'section_memberships/destroy', to: 'section_memberships#destroy', as: 'destroy_membership'

  get '/activate/:id', to: 'account_activations#activate', as: 'activate'
  get '/promote/:id', to: 'account_activations#promote_to_member', as: 'promote'

  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/about',  to: 'static_pages#about'

  get '/rules', to: 'static_pages#rules'

root 'static_pages#home'

resources :users
resources :section_memberships, only: [:destroy, :create]
resources :sections, only: [:index, :show]
resources :projects, only: [:index, :show, :new, :update, :destroy]
resources :raports, only: [:new, :show, :create]
resources :materials
resources :object_types
resources :things
resources :project_things_relations, only: [:create, :destroy]


end

app/models/material.rb
class Material < ApplicationRecord
  default_scope -> { order(:updated_at)}
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :amount, presence: true
  validates :category, presence: true
  belongs_to :supervisor, class_name: "User", optional: true



  def self.search(pattern)
    if pattern.blank?  # blank? covers both nil and empty string
      all
    else
      left_outer_joins(:supervisor).where(
        "materials.name LIKE ? OR
         materials.category LIKE ? OR
         CAST(materials.amount AS TEXT) LIKE ? OR
         materials.note LIKE ? OR
         users.name || ' ' || users.surname LIKE ? OR
        CAST(materials.id AS TEXT) LIKE ?",
        "%#{pattern}%","%#{pattern}%",
        "#{pattern}","%#{pattern}%","%#{pattern}%",
        "#{pattern}")
    end
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update]
  before_action :member_user, only: [:new, :create]

  def new
    @material = Material.new(supervisor_id: current_user.id)
    @categories = list_categories
  end

  def create
    @material = Material.new(material_params)
    if @material.save
      flash[:success] = "Materiał dodany pomyślnie!"
      redirect_to materials_path
    else
      flash[:danger] = "Niepoprawny przedmiot"
      render 'new'
    end
  end

  def update
    @material = Material.find(params[:id])
    if @material.update_attributes(material_params)
       flash[:success] = "Materiał eksploatacyjny pomyślnie zaktualizowany"
      redirect_to @material
    else
      render 'edit'
    end
  end

  def show
    @material = Material.find(params[:id])
    @user = @material.supervisor
  end

  def index
    @materials = Material.search(params[:term]).paginate(page: params[:page])
  end

  def edit
    @material = Material.find(params[:id])
    @categories = list_categories
  end


  private
  def material_params
    params.require(:material).permit(:name, :supervisor_id, :note, :category, :amount)
  end


end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/edit.html.erb
<% provide(:title, "Edycja materiału") %>
<h1>Zmień liczbę sztuk <%= "(lub edytuj parametry)" if current_user.member? %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@material) do |f| %>

      <%= f.label :amount, "Ilość"%>
      <%= f.text_field :amount, class: 'form-control' %>

      <% if current_user.member? %>

      <%= f.label :name, "Nazwa" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%=  f.collection_select(:category, @categories, :to_s, :to_s) %>
      <%= f.hidden_field  :supervisor_id  %>

      <h2>Opcjonalne</h2>
      <%= f.label :note, "Uwagi" %>
      <%= f.text_field :note, class: 'form-control' %>

      <% else %>

      <%= f.hidden_field :name, class: 'form-control' %>

      <%=  f.hidden_field :category %>
      <%= f.hidden_field  :supervisor_id  %>

      <%= f.hidden_field :note %>


      <% end %>

      <%= f.submit "Wyślij formularz", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/materials/index.html.erb
<% provide(:title, 'Materiały') %>
<h1>Posiadane przez koło materiały</h1>

<%= form_tag(materials_path, method: :get) do %>
  <%= text_field_tag :term, params[:term] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<%= will_paginate %>
<% if current_user.member?  %>
  <h2><%= link_to "Dodaj materiał eksploatacyjny", new_material_path %></h2>
<% end%>
<ol class="sections">
  <% @materials.each do |material| %>
      <li>
            <%= link_to material.name, material_path(material)  %>
            <%= "Ilość: #{material.amount} |  " %>
            <%= link_to "zmień ilość", edit_material_path(material) if current_user.member? %>
      </li>
    <% end %>
</ol>
<%= will_paginate %>

app/views/materials/new.html.erb
<% provide(:title, 'Dodaj materiał') %>
<h1>Wprowadź cechy materiału</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@material, url: materials_path) do |f| %>

      <%= f.label :name, "Nazwa" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :amount, "Ilość"%>
      <%= f.text_field :amount, class: 'form-control' %>

      <%=  f.collection_select(:category, @categories, :to_s, :to_s) %>
      <%= f.hidden_field  :supervisor_id  %>

      <h2>Opcjonalne</h2>
      <%= f.label :note, "Uwagi" %>
      <%= f.text_field :note, class: 'form-control' %>

      <%= f.submit "Wyślij formularz", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/materials/show.html.erb
<% provide(:title, @material.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @material.name %>
        <% if current_user.member? %>
         <%= link_to "(Edytuj)", edit_material_path(@material) %>
        <%end%>
      </h1>
      </br>
        Liczba sztuk: <%= @material.amount %></br>
        Kategoria: <%= @material.category %></br>
        Opiekun: <%=  @user.nil? ? "---" : "#{@user.name} #{@user.surname}"%></br>
        Data dodania: <%=  @material.created_at %></br>
        Data ostatniej aktualizacji: <%= @material.updated_at %></br>
        Uwagi: <%= @material.note %>
    </section>
  </aside>
</div>